// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"davidasrobot2/go-boilerplate/config"
	"davidasrobot2/go-boilerplate/internal/app/http/handler"
	"davidasrobot2/go-boilerplate/internal/app/http/router"
	"davidasrobot2/go-boilerplate/internal/repository"
	"davidasrobot2/go-boilerplate/internal/usecase"
	"davidasrobot2/go-boilerplate/pkg/auth"
	"davidasrobot2/go-boilerplate/pkg/database/orm"
	"davidasrobot2/go-boilerplate/pkg/logger"
	"davidasrobot2/go-boilerplate/pkg/server"
	"davidasrobot2/go-boilerplate/pkg/validator"
	"log/slog"

	"github.com/gofiber/fiber/v2"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp initializes the application and its dependencies.
func InitializeApp() (*App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := orm.NewGormDB(configConfig)
	if err != nil {
		return nil, err
	}
	slogLogger := logger.NewLogger()
	app := server.NewFiberServer(slogLogger)
	userRepository := repository.NewUserRepository(db, slogLogger)
	jwtGenerator := auth.NewJWTGenerator(configConfig)
	userUsecase := usecase.NewUserUsecase(slogLogger, userRepository, jwtGenerator)
	validate := validator.NewValidator()
	userHandler := handler.NewUserHandler(slogLogger, userUsecase, validate)
	administratorRepository := repository.NewAdministratorRepository(db)
	administratorUsecase := usecase.NewAdministratorUsecase(administratorRepository, jwtGenerator)
	adminHandler := handler.NewAdminHandler(administratorUsecase, validate)
	routerRouter := router.NewRouter(configConfig, app, userHandler, adminHandler)
	diApp := NewApp(configConfig, db, slogLogger, app, routerRouter)
	return diApp, nil
}

// wire.go:

// App is the main application container.
type App struct {
	Cfg    *config.Config
	DB     *gorm.DB
	Logger *slog.Logger
	Server *fiber.App

	// Router
	Router *router.Router
}

// NewApp creates a new application.
func NewApp(cfg *config.Config, db *gorm.DB, logger2 *slog.Logger, server2 *fiber.App, router2 *router.Router) *App {
	return &App{
		Cfg:    cfg,
		DB:     db,
		Logger: logger2,
		Server: server2,
		Router: router2,
	}
}

// Start runs the application.
func (a *App) Start() error {
	a.Router.RegisterRoutes()
	a.Logger.Info("Starting server", "port", a.Cfg.App.Port)
	return a.Server.Listen(":" + a.Cfg.App.Port)
}

// RegisterRoutes is a convenience method to register routes. It's called by Start.
func (a *App) RegisterRoutes() {
	a.Router.RegisterRoutes()
}
