//go:build wireinject
// +build wireinject

package di

import (
	"davidasrobot2/go-boilerplate/config"
	"davidasrobot2/go-boilerplate/internal/app/http/handler"
	"davidasrobot2/go-boilerplate/internal/app/http/router"
	"davidasrobot2/go-boilerplate/internal/repository"
	"davidasrobot2/go-boilerplate/internal/usecase"
	"davidasrobot2/go-boilerplate/pkg/auth"
	"davidasrobot2/go-boilerplate/pkg/database/orm"
	"davidasrobot2/go-boilerplate/pkg/logger"
	"davidasrobot2/go-boilerplate/pkg/server"
	"davidasrobot2/go-boilerplate/pkg/validator"
	"log/slog"

	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// App is the main application container.
type App struct {
	Cfg    *config.Config
	DB     *gorm.DB
	Logger *slog.Logger
	Server *fiber.App

	// Router
	Router *router.Router
}

// NewApp creates a new application.
func NewApp(cfg *config.Config, db *gorm.DB, logger *slog.Logger, server *fiber.App, router *router.Router) *App {
	return &App{
		Cfg:    cfg,
		DB:     db,
		Logger: logger,
		Server: server,
		Router: router,
	}
}

// Start runs the application.
func (a *App) Start() error {
	a.Router.RegisterRoutes()
	a.Logger.Info("Starting server", "port", a.Cfg.App.Port)
	return a.Server.Listen(":" + a.Cfg.App.Port)
}

// RegisterRoutes is a convenience method to register routes. It's called by Start.
func (a *App) RegisterRoutes() {
	a.Router.RegisterRoutes()
}

// InitializeApp initializes the application and its dependencies.
func InitializeApp() (*App, error) {
	wire.Build(
		// Configuration
		config.Providers,
		// Logger
		logger.Providers,
		// Database
		orm.Providers,
		// Validator
		validator.Providers,
		// Auth
		auth.Providers,
		// Server
		server.Providers, // This will now use NewFiberServer
		// Repositories
		repository.Providers,
		// Usecases
		usecase.Providers,
		// Handlers
		handler.UserHandlerSet,
		handler.AdminHandlerSet,
		// Router
		router.RouterSet,
		// Main App
		wire.NewSet(NewApp),
	)
	return nil, nil // Will be generated by Wire
}
