package constant

import (
	"errors"
)

var (
	ErrorMessageProcessFailed          = errors.New("something went wrong, please try again later")
	ErrorMessageNotFound               = errors.New("record not found")
	ErrorMessageMissingOrMalformedJWT  = errors.New("Missing or malformed JWT")
	ErrorMessageInvalidCredential      = errors.New("invalid credential")
	ErrorMessageInvalidToken           = errors.New("invalid token")
	ErrorMessageTokenExpired           = errors.New("token expired")
	ErrorMessageBadRequest             = errors.New("bad request")
	ErrorMessageInternalServerError    = errors.New("internal server error")
	ErrorMessageServiceUnavailable     = errors.New("service unavailable")
	ErrorMessageGatewayTimeout         = errors.New("gateway timeout")
	ErrorMessageInvalidRequest         = errors.New("invalid request")
	ErrorMessageUnauthorized           = errors.New("unauthorized")
	ErrorMessageForbidden              = errors.New("forbidden")
	ErrorMessageTooManyRequests        = errors.New("too many requests")
	ErrorMessageMethodNotAllowed       = errors.New("method not allowed")
	ErrorMessagePayloadTooLarge        = errors.New("payload too large")
	ErrorMessageUnsupportedMediaType   = errors.New("unsupported media type")
	ErrorMessageInvalidRequestBody     = errors.New("invalid request body")
	ErrorMessageConflict               = errors.New("conflict")
	ErrorMessageUserAlreadyHasMerchant = errors.New("merchant already exist")

	// ErrorMessageUserNotFound                 = errors.New("user not found")
	// ErrorMessageUserAlreadyExists            = errors.New("user already exists")
	// ErrorMessageRefreshTokenExpired          = errors.New("token is expired")
	// ErrorMessageInvalidID                    = errors.New("invalid ID format")
	// ErrorMessageInvalidEmail                 = errors.New("invalid email format")
	// ErrorMessageInvalidUsername              = errors.New("invalid username")
	// ErrorMessageInvalidPhone                 = errors.New("invalid phone number")
	// ErrorMessageInvalidInput                 = errors.New("invalid input data")
	// ErrorMessageInvalidUsernameOrPassword    = errors.New("invalid username or password")
	// ErrorMessageInvalidPIN                   = errors.New("invalid PIN code")
	// ErrorMessagePhoneNumberAlreadyRegistered = errors.New("phone number already registered")
	// ErrorMessageEmailAlreadyRegistered       = errors.New("email already registered")
	// ErrorMessageUsernameAlreadyRegistered    = errors.New("username already registered")
	// ErrorMessageUserNotHoster                = errors.New("user is not a hoster")
	// ErrorMessageUserAlreadyHoster            = errors.New("user is already a hoster")
	// ErrorMessageUploadIdentityImageFailed    = errors.New("failed to upload identity image")
	// ErrorPropertyMissing                     = errors.New("no value given for required property value")
)
